### ISSUE TITLE
Coloured scroll bars

### ISSUE THREAD

**Issue by micahdbak** [CSSS/csss-site-frontend#18]
Scroll bars are white by default, for light-themed browsers.
Can look ugly with the colour-scheme we're going for.

Maybe style it with a CSS file?
Needs updating to /src/_shared/VSCode/Page.js, for the component displaying the children of that component.

**Comment by micahdbak** [comment]
@EarthenSky - interested maybe?

**Comment by micahdbak** [comment]
@EarthenSky - this isn't really needed anymore, did you still want to work on this?

**Comment by EarthenSky** [comment]
nope, it seems not super necessary for the time being

**Comment by micahdbak** [comment]
Kewl, I'll close it then, we can reopen if it comes up again
