### ISSUE TITLE
what's up with the login redirect?

### ISSUE THREAD

**Issue by modernNeo** [CSSS/csss-site-frontend#24]
happened to take a gander at the new website and noticed this is the login url
`https://cas.sfu.ca/cas/login?service=https://api.sfucsss.org/auth/login%3Fnext%3Dhttps://new.sfucsss.org/#profile`
breaking that down
you are asking SFU'S to redirect to `https://api.sfucsss.org/auth/login%3Fnext%3Dhttps://new.sfucsss.org/#profile` upon successful login

and if I break that part down further, I assume you are trying to get the website's backend to redirect to `https://new.sfucsss.org/#profile` upon successful login?

**Comment by micahdbak** [comment]
Yes correct!

**Comment by modernNeo** [comment]
I assume you are passing `https://new.sfucsss.org/#profile` to the backend so that when you have the website at the point where a user can login from any page, you can place them right back where they were when they hit the login button?

**Comment by micahdbak** [comment]
Exactly!

**Comment by micahdbak** [comment]
That is the goal :)

**Comment by modernNeo** [comment]
so why not instead just do `https://api.sfucsss.org/auth/login?redirect=profile`?

pass in the page to redirect the user to on the front-end rather than pass in the entire url of the front-end?

I assume the back-end knows the fqdn of the front-end so its kinda redundant to give it a fqdn it already knows and thereby you can also make the url cleaner and simpler

**Comment by micahdbak** [comment]
Not gonna lie, that's a great idea. Providing less would be cleaner. I think the original idea was to handle other subdomains too, but I don't think we plan on doing that anymore, based on the current design of the frontend. I'll make this an issue in the backend for me to do 😉

And regardless, a different subdomain or other could just be another search param provided; e.g., `?subdomain=pacmacro`, or something

**Comment by modernNeo** [comment]
> I think the original idea was to handle other subdomains too, but I don't think we plan on doing that anymore

oh, now I am curious, what other subdomains?

**Comment by micahdbak** [comment]
I was thinking to maybe have the subdomain pacmacro.sfucsss.org or pac.sfucsss.org point to one of my personal servers, cuz I wrote last year's implementation in Go. But this is all speculative ATM, nothing definitive
