### ISSUE TITLE
Fix /src/_shared/VSCode/Page.js's dynamic scaling for mobile pages

### ISSUE THREAD

**Issue by micahdbak** [CSSS/csss-site-frontend#31]
Fault is probably in /src/main/components/Page.js, but maybe in the VSCode component too

**Comment by EarthenSky** [comment]
What was the issue with dynamic scaling that needed to be fixed?

**Comment by micahdbak** [comment]
Issue was (in a step-by-step fashion):
- Open site
- Scale window - dynamic scaling works
- Click on a different page
- Scale window - dynamic scaling wasn't working

The problem was loading a different page with hash routing wasn't considered a page refresh with React's `useEffect` - so it wasn't resetting the media query callback function with the refreshed Page component.

The fix was reworking the `useEffect` and media query handling to work with extra refreshes

**Comment by micahdbak** [comment]
@EarthenSky ^^^
