### ISSUE TITLE
Make Common Rooms page in main app

### ISSUE THREAD

**Issue by micahdbak** [CSSS/csss-site-frontend#45]
/src/main/index.js
```js
// ...
import { /* ... */, CommonRooms } from './pages';

// ...

const router = createHashRouter([
  // ...
  { path: '/common_rooms', element: <CommonRooms /> },
  // ...
]);
```

/src/main/pages/CommonRooms.js
```js
import React from 'react';
import { Page } from '../components';

export const CommonRooms = () => {
  return (
    <Page>
      {/* ... */}
    </Page>
  );
};
```

**Comment by micahdbak** [comment]
@gunmack 

Visual reference: https://ubccsss.org/cube/ (of course, feel free to go in your own direction if you'd like)

Should contain:

- Photo of ASB 9802 + description of the room + directions (maybe link to SFU map?)
- Photo of ASB 9971 + description of the room + directions (maybe link to SFU map?)
- Information about our vending machines + items (typically) sold + the costs
  - Maybe put a photo of a vending machine?
- Footer (use the component provided in /src/main/components/Footer.js - for reference, see how its used in /src/main/pages/Home.js)

To make this page, create the file /src/main/pages/CommonRooms.js, copying the general structure found in the other files under /src/main/pages (i.e., using the /src/main/components/Page.js component, Footer.js component).

You'll need to update the /src/main/index.js file's router definition to include a line for '/common_rooms' with the element being the component exported by /src/main/pages/CommonRooms.js.

Go crazy! LMK if you run into issues setting up node/npm! (Start by reading through the README.md on how to get setup. Use WSL if you're on windows!)

**Comment by micahdbak** [comment]
@gunmack - progress?

**Comment by gunmack** [comment]
#58

**Comment by micahdbak** [comment]
finished by @gunmack <3
