### ISSUE TITLE
Gabe get node and npm working properly

### ISSUE THREAD

**Issue by micahdbak** [CSSS/csss-site-frontend#50]

**Comment by micahdbak** [comment]
:eyes:

**Comment by EarthenSky** [comment]
hahaha, okie!

**Comment by micahdbak** [comment]
yay!

**Comment by micahdbak** [comment]
@EarthenSky progress?

**Comment by EarthenSky** [comment]
I worked on non-react website last night, though I notice you assigned me some react issues, so I'm forced to get it working properly by then \:)

**Comment by micahdbak** [comment]
YAY

**Comment by micahdbak** [comment]
Remember, ask me for help if needed, especially if it takes you more than 15 minutes to get set up

**Comment by EarthenSky** [comment]
completed! The solution was to `npm run start` hahahahahahahahaha.....
