### ISSUE TITLE
Make the bottom status bar's branch name clickable

### ISSUE THREAD

**Issue by micahdbak** [CSSS/csss-site-frontend#56]
Please make it redirect to https://github.com/CSSS/csss-site-frontend :)

**Comment by micahdbak** [comment]
@Darrickg it's in /src/_shared/react/VSCode/Page.js, line 80

**Comment by micahdbak** [comment]
get off ur booty and do this @Darrickg

**Comment by Darrickg** [comment]
this too now that i am free er from orientation stuff

**Comment by micahdbak** [comment]
@Darrickg do it :))

**Comment by Darrickg** [comment]
is this still in page.js line 80?

**Comment by micahdbak** [comment]
@Darrickg im gonna close this

**Comment by micahdbak** [comment]
@Darrickg jk im just gonna do it real quick
