### ISSUE TITLE
Upgrade common room page

### ISSUE THREAD

**Issue by micahdbak** [CSSS/csss-site-frontend#69]
This page is a bit more topical now that the old common room is kil.

Maybe rework the page to just talk about the new common room? We can just use the existing photo of the new room and we can upgrade it later when the room is better set up.

If you wanna be cool, feel free to add a "RIP" section in the bottom of the page in memoriam of the old common room.

Also prices for snacks and drinks will be the same so keep those tables - the machines will be in the new room!

**Comment by micahdbak** [comment]
@gunmack are you interested in this or want it to be delegated to someone else?

**Comment by gunmack** [comment]
> @gunmack are you interested in this or want it to be delegated to someone else?

I got it

**Comment by StaticMemory** [comment]
issue 69 hehehehe

**Comment by micahdbak** [comment]
> issue 69 hehehehe

hehehehe

**Comment by gunmack** [comment]
Moved to https://github.com/CSSS/csss-site-frontend/issues/75
